name: "Run Tests ğŸ“¢ "
on:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platfrom: [ubuntu-latest, macos-latest]
    name: "Run Tests ğŸ“¢ "
    runs-on: ${{ matrix.platfrom }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.1'
      - uses: arduino/setup-task@v1
        with:
          version: 3.11.0
      - name: Build
        id: build
        run: task gen && go build -v ./...
      - name: Run Tests
        id: test
        run: go test -v ./...
